- hosts: localhost
  gather_facts: no
  tasks: 
  - name: calico
    tags: calico
    shell: kubectl apply -f calico.yaml
  - name: ceph-crds
    shell: kubectl create -f crds.yaml -f common.yaml -f operator.yaml
  # - name: ceph-common
  #   shell: kubectl create -f https://raw.githubusercontent.com/rook/rook/release-1.5/cluster/examples/kubernetes/ceph/common.yaml
  # - name: ceph-keyring
  #   shell: kubectl -n rook-ceph create secret generic --type kubernetes.io/rook rook-ceph-crash-collector-keyring
  - name: ceph-cluster
    shell: kubectl create -f ceph_cluster.yaml
  - name: ceph-pool-ssd
    shell: kubectl create -f ceph_pool_ssd.yaml
  - name: storage-class-ssd
    shell: kubectl create -f storageclass_ssd.yaml
  - name: ceph-mds
    shell: kubectl create -f filesystem.yaml
  - name: storage-class-cephfs
    shell: kubeclt create -f storageclass_cephfs.yaml
  - name: ceph-object
    shell: kubectl create -f object.yaml
  - name: storage-class-object
    shell: kubectl create -f storageclass_obeject_delete.yaml -f storageclass_object_retain.yaml
  - name: metallb-ns
    shell: kubectl apply -f namespace.yaml
  - name: metallb-op
    shell: kubectl apply -f metallb.yaml
  - name: metallb-secret
    shell: kubectl create secret generic -n metallb-system memberlist --from-literal=secretkey="$(openssl rand -base64 128)"
  - name: metallb-ip-pool
    shell: k create -f metallb-config.yaml
  - name: prometheus ns
    shell: k create ns monitoring
  - name: helm repo
    shell: helm repo add prometheus-community https://prometheus-community.github.io/helm-charts && helm repo update
  - name: prometheus install
    shell: helm -n monitoring install -f prometheus_operator_customize.yaml prom prometheus-community/kube-prometheus-stack 